### PR TITLE
Ud 671 factories

### PR DESCRIPTION
**Pull request by olexii4**
@ashumilova  WDYT?

### CODE REVIEW

**Comment by benoitf** [comment]
The two UD-672 commits can't be merged into one commit ? (as there are intermediate changes)

**Comment by olexii4** [comment]
Done

**Comment by benoitf** [comment]
I've reviewed code and now it's ok for me. Thx for the updates.
I think you'll need a go from Stevan if UI is ok

**Comment by olexii4** [comment]
Done

**Pull request merged**
