### PR TITLE
update che-dashboard dependency location

### PR DESCRIPTION
**Pull request by riuvshin**
@benoitf @ashumilova WDYT?

### CODE REVIEW

**Comment by benoitf** [comment]
it misses fix at https://github.com/codenvy/dashboard/blob/master/gulp/styles.js#L28 and https://github.com/codenvy/dashboard/blob/master/gulp/styles.js#L36-L37

**Comment by benoitf** [comment]
and https://github.com/codenvy/dashboard/blob/master/bower.json#L54-L57 needs to be updated to correct path

**Comment by riuvshin** [comment]
@benoitf pr updated

**Comment by benoitf** [comment]
+1 (but you need another binding +1) @ashumilova @olexii4 @akurinnoy

**Comment by riuvshin** [comment]
@benoitf sure :) thanks for helping on that!

**Comment by ashumilova** [comment]
+1

**Pull request merged**
