### PR TITLE
Fix license headers

### PR DESCRIPTION
**Pull request by riuvshin**
@skabashnyuk @benoitf please review

### CODE REVIEW

**Comment by benoitf** [comment]
It can only be 2015-2016 for these files

**Comment by riuvshin** [comment]
we have single rule for all files.

**Comment by benoitf** [comment]
it is customized for each repo 
Copyright header is only valid for files introduced at a given time
I will update

**Comment by riuvshin** [comment]
ah sure, in pom. ok

**Comment by benoitf** [comment]
it was not including some files I fix it with another PR

**Pull request closed without merging**
