### PR TITLE
CODENVY-232: add recent factories box to dashboard view

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@codenvy.com>
selection_073

### CODE REVIEW

**Comment by TylerJewell** [comment]
Why do we show the ID on the recent factories?  It's gibberish to the end user.  No one knows what the ID is. We should only show pretty name.

**Comment by ashumilova** [comment]
if there is no pretty name - we show the id, but maybe better to show URL instead (when no pretty name)

**Comment by olexii4** [comment]
We show the name of the factory and its ID.  In this case I used a minimal template. That is why we didn't see any name.

**Comment by olexii4** [comment]
selection_074

**Comment by ashumilova** [comment]
+1

**Comment by olexii4** [comment]
+1
I guess we should change widget of factory (factoryId to URL)

**Comment by olexii4** [comment]
@slemeur  WDYT?

**Comment by slemeur** [comment]
Let's show the factory URL instead of the factoryID.
This way, if there is no pretty name, we show only the factory URL

**Comment by olexii4** [comment]
selection_075

**Comment by ashumilova** [comment]
+1

**Comment by akurinnoy** [comment]
+1

**Comment by slemeur** [comment]
Looks good, I just want to check how does it look when you have only the URL? Is the URL is vertically centered in the box?

**Comment by olexii4** [comment]
selection_076

**Comment by slemeur** [comment]
+1

**Pull request merged**
