### PR TITLE
UD-788: Change authorization token request for github

### PR DESCRIPTION
**Pull request by olexii4**
@ashumilova WDYT?

### CODE REVIEW

**Comment by riuvshin** [comment]
Please Perform release after merge this fix.

**Comment by olexii4** [comment]
@sleshchenko should add own changes to the server-side

**Comment by ashumilova** [comment]
OK to merge after changes are applied on server side.

**Comment by sleshchenko** [comment]
I did merge my changes https://github.com/codenvy/che-core/commit/415b230a65cd3cc4954c9209da409048bfe64ad1

**Pull request merged**
